apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pg-admin-pv-claim
  namespace: questionarios
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 3Gi
