apiVersion: v1
kind: Secret
metadata:
  name: mypostgres-secret
  namespace: questionarios
type: Opaque
stringData:
  superUserPassword: postgresSuperUserPsw
  replicationUserPassword: postgresReplicaPsw
---
apiVersion: kubegres.reactive-tech.io/v1
kind: Kubegres
metadata:
  name: mypostgres
  namespace: questionarios

spec:

  replicas: 3
  image: postgres:14

  database:
    size: 200Mi

  env:
    - name: POSTGRES_PASSWORD
      valueFrom:
        secretKeyRef:
          name: mypostgres-secret
          key: superUserPassword

    - name: POSTGRES_REPLICATION_PASSWORD
      valueFrom:
        secretKeyRef:
          name: mypostgres-secret
          key: replicationUserPassword
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: pg-admin
  namespace: questionarios
  labels:
    app.kubernetes.io/name: pg-admin
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: pg-admin
  replicas: 1
  template:
    metadata:
      labels:
        app.kubernetes.io/name: pg-admin
    spec:
      containers:
        - name: pg-admin
          image: dpage/pgadmin4
          ports:
            - containerPort: 80
          env:
            - name: PGADMIN_DEFAULT_EMAIL
              value: user@domain.com
            - name: PGADMIN_DEFAULT_PASSWORD
              value: SuperSecret
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app.kubernetes.io/name: pg-admin
  name: pg-admin
  namespace: questionarios
spec:
  ports:
    - name: http
      port: 80
      targetPort: 80
  selector:
    app.kubernetes.io/name: pg-admin
  type: ClusterIP
