---
apiVersion: v1
kind: ServiceAccount
metadata:
  annotations:
    app.quarkus.io/commit-id: 93bbd64beba2d1cce08a61daabfb2f8410ed5db8
    app.quarkus.io/build-timestamp: 2021-11-10 - 16:34:55 +0000
  labels:
    app.kubernetes.io/version: 1.0.4-SNAPSHOT
    app.kubernetes.io/name: questionarios-api
  name: questionarios-api
  namespace: questionarios
---
apiVersion: v1
kind: Service
metadata:
  annotations:
    app.quarkus.io/commit-id: 93bbd64beba2d1cce08a61daabfb2f8410ed5db8
    app.quarkus.io/build-timestamp: 2021-11-10 - 16:34:55 +0000
  labels:
    app.kubernetes.io/name: questionarios-api
    app.kubernetes.io/version: 1.0.4-SNAPSHOT
  name: questionarios-api
  namespace: questionarios
spec:
  ports:
    - name: http
      port: 80
      targetPort: 8080
  selector:
    app.kubernetes.io/name: questionarios-api
    app.kubernetes.io/version: 1.0.4-SNAPSHOT
  type: ClusterIP
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: view-secrets
  namespace: questionarios
rules:
  - apiGroups:
      - ""
    resources:
      - secrets
    verbs:
      - get
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: questionarios-api-view
  namespace: questionarios
roleRef:
  kind: ClusterRole
  apiGroup: rbac.authorization.k8s.io
  name: view
subjects:
  - kind: ServiceAccount
    name: questionarios-api
    namespace: questionarios
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: questionarios-api-view-secrets
  namespace: questionarios
roleRef:
  kind: Role
  apiGroup: rbac.authorization.k8s.io
  name: view-secrets
subjects:
  - kind: ServiceAccount
    name: questionarios-api
    namespace: questionarios
---
apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    app.quarkus.io/commit-id: 93bbd64beba2d1cce08a61daabfb2f8410ed5db8
    app.quarkus.io/build-timestamp: 2021-11-10 - 16:34:55 +0000
  labels:
    app.kubernetes.io/version: 1.0.4-SNAPSHOT
    app.kubernetes.io/name: questionarios-api
  name: questionarios-api
  namespace: questionarios
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/version: 1.0.4-SNAPSHOT
      app.kubernetes.io/name: questionarios-api
  template:
    metadata:
      annotations:
        app.quarkus.io/commit-id: 93bbd64beba2d1cce08a61daabfb2f8410ed5db8
        app.quarkus.io/build-timestamp: 2021-11-10 - 16:34:55 +0000
      labels:
        app.kubernetes.io/version: 1.0.4-SNAPSHOT
        app.kubernetes.io/name: questionarios-api
      namespace: questionarios
    spec:
      containers:
        - env:
            - name: KUBERNETES_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
          image: alejandrotrilla/questionarios-api:1.0.4-SNAPSHOT
          imagePullPolicy: Always
          livenessProbe:
            failureThreshold: 3
            httpGet:
              path: /q/health/live
              port: 8080
              scheme: HTTP
            initialDelaySeconds: 0
            periodSeconds: 30
            successThreshold: 1
            timeoutSeconds: 10
          name: questionarios-api
          ports:
            - containerPort: 8080
              name: http
              protocol: TCP
          readinessProbe:
            failureThreshold: 3
            httpGet:
              path: /q/health/ready
              port: 8080
              scheme: HTTP
            initialDelaySeconds: 20
            periodSeconds: 45
            successThreshold: 1
            timeoutSeconds: 10
          resources:
            limits:
              cpu: 1000m
              memory: 512Mi
            requests:
              cpu: 250m
              memory: 64Mi
      serviceAccount: questionarios-api
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  annotations:
    app.quarkus.io/commit-id: 93bbd64beba2d1cce08a61daabfb2f8410ed5db8
    app.quarkus.io/build-timestamp: 2021-11-10 - 16:34:55 +0000
  labels:
    app.kubernetes.io/name: questionarios-api
    app.kubernetes.io/version: 1.0.4-SNAPSHOT
  name: questionarios-api
  namespace: questionarios
spec:
  rules:
    - host: questionarios.com.ar
      http:
        paths:
          - backend:
              service:
                name: questionarios-api
                port:
                  name: http
            path: /
            pathType: Prefix
